#https://surrealdb.com/docs/cli/start
version: "3.9"
services:

  db:
    container_name: db
    image: ${DB_IMAGE}
    volumes:
      - ./data:/data
#    ports:
#      - "27275:8000"
    command:
      - start
      - --log=warn
      - --user=${DB_USER}
      - --pass=${DB_PASS}
      - file://data/database.db
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  node:
    container_name: node
    image: ${NODE_IMAGE}
    working_dir: /home/node
    command: bash -c "node ./server/index.mjs"
    volumes:
      - ./prod:/home/node
    tty: true
    restart: unless-stopped
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  nginx:
    container_name: nginx
    image: ${NGINX_IMAGE}
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - ./cert:/var/cert
      - ./cert/conf:/etc/letsencrypt
      - ./cert/www:/var/www/certbot

    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - node

  certbot:
    image: ${CERTBOT_IMAGE}
    container_name: certbot
    volumes:
      - ./cert/conf:/etc/letsencrypt
      - ./cert/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx